---

en-GB:
  groove_description_dash: "Ryota dashes through rows of enemies, dealing 50% of the damage he would inflict at full health."
  groove_description_splash_jump: "Ragna leaps into the air. Upon landing she deals 50% of the damage she would inflict at full health to surrounding units."
  
...